version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.14
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: welcome
        databases:
          default:
            connector: postgres
            host: 10.0.2.2
            port: '5432'
            database: test04
            user: postgres
            password: postgres
            migrations: true